[tasks.default]
description = "Runs on `cargo make`"
category = "Development"
alias = "dev-test-flow"

[tasks.dev-test-flow]
description = "Development testing flow will first format the code, and than run cargo build and test"
category = "Development"
dependencies = [
	"touch-lib",
    "format-flow",
	"clippy",
    "pre-build",
    "build",
    "post-build",
	"pre-docs",
    "docs",
    "post-docs",
    "test-flow"
]

[tasks.touch-lib]
command = "touch"
args = ["src/lib.rs"]

[tasks.clippy]
args = ["clippy", "--", "-D", "warnings", "-W", "clippy::pedantic"]

[tasks.format-stable]
description = "Runs the cargo rustfmt plugin."
category = "Development"
condition = { channels = [ "stable", "beta" ] }
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]
