name: Rust

on: [push, pull_request]

env:
  CARGO_UNSTABLE_SPARSE_REGISTRY: true

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /acheron
    container:
      image: ghcr.io/robbiemckinstry/acheron-base:nightly
      options: --security-opt seccomp=unconfined
      credentials:
       username: ${{ github.actor }}
       password: ${{ secrets.PACKAGES_ACCESS_TOKEN }}
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v3
      - name: Run Cargo Make
        uses: actions-rs/cargo@v1.0.1
        with:
          command: make 
          args: ci-flow
      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: acheron 
          verbose: true
          fail_ci_if_error: true
